#!/bin/sh
#
# omadaenv.sh
# Script called by omada.service to create the service environment file.
# The environment file is processes just prior to execution of service
# executable.


NAME="omada"
DESC="Omada Controller"

OMADA_HOME="/opt/tplink/EAPController"
LOG_DIR="${OMADA_HOME}/logs"
WORK_DIR="${OMADA_HOME}/work"
DATA_DIR="${OMADA_HOME}/data"
PROPERTY_DIR="${OMADA_HOME}/properties"
AUTOBACKUP_DIR="${DATA_DIR}/autobackup"

XDG_CONFIG_HOME="${DATA_DIR}/chromium"

JRE_HOME="$( readlink -f "$( which java )" | sed "s:bin/.*$::" )"
JAVA_TOOL="${JRE_HOME}/bin/java"
CLASSPATH="/usr/share/java/commons-daemon.jar:${OMADA_HOME}/lib/*:${PROPERTY_DIR}"
MAIN_CLASS="com.tplink.smb.omada.starter.OmadaLinuxMain"
JAVA_OPTS="-server -XX:MaxHeapFreeRatio=60 -XX:MinHeapFreeRatio=30 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=${LOG_DIR}/java_heapdump.hprof -Djava.awt.headless=true -Djdk.lang.Process.launchMechanism=vfork"
STARTUP_INFO_PATH="${OMADA_HOME}/data/startupInfo"

OMADA_USER=${OMADA_USER:-omada}
OMADA_GROUP=$(id -gn ${OMADA_USER})

PID_FILE="/run/${NAME}.pid"

cat << EOF > /tmp/omada.env
NAME="${NAME}"
DESC="${DESC}"
OMADA_HOME="${OMADA_HOME}"
LOG_DIR="${LOG_DIR}"
WORK_DIR="${WORK_DIR}"
DATA_DIR="${DATA_DIR}"
PROPERTY_DIR="${PROPERTY_DIR}"
AUTOBACKUP_DIR="${AUTOBACKUP_DIR}"

XDG_CONFIG_HOME="${XDG_CONFIG_HOME}"

JRE_HOME="${JRE_HOME}"
JAVA_TOOL="${JAVA_TOOL}"
CLASSPATH="${CLASSPATH}"
JAVA_OPTS="${JAVA_OPTS}"
MAIN_CLASS="${MAIN_CLASS}"
STARTUP_INFO_PATH="${STARTUP_INFO_PATH}"

OMADA_USER="${OMADA_USER}"
OMADA_GROUP="${OMADA_GROUP}"

PID_FILE="${PID_FILE}"
END
